/**:
  ros__parameters:
    link_layer: "ethernet" # "ethernet" | "cube-evk" | "cohda"
    target_device: "lo" # Should be the IP address of the target device or the network interface name
    gpsd_host: "127.0.0.1"
    gpsd_port: "2947"
    is_sender: true
    publish_own_cams: false
    cam_enabled: true
    cpm_enabled: true
    security: "none"
    certificate: ""
    certificate-key: ""
    certificate-chain:
      - ""
